@startuml Forgot password
participant Client
participant Backend
database db
collections Redis
participant EmailService

Client -> Backend: forgot password
Backend -> db: check user
alt User not found
  db -> Backend: user not found
  Backend -> Client: user not found
  else user found
  db -> Backend: user found
  Backend -> Redis: store otp
  Backend -> EmailService: send email otp
  Backend -> Backend: create otp authId
  Backend -> Client: otp sent
  Client -> Backend: enter otp
end

Backend -> Redis: check otp
  alt otp incorrect
    Redis -> Backend: otp incorrect
    Backend -> Client: otp incorrect
    else otp correct
    Redis -> Backend: otp correct
    Backend -> Redis: delete otp
    Backend -> Backend: create login authId
    Backend -> Client: send authId
    Client -> Client: store authId
    Client -> Backend: send new password
    Backend -> db: update password
    Backend -> Backend: create token
    Backend -> Client: login success
    Client -> Client: store token
  end


@enduml